version: '3.7'

services:
  portdomainservice:
    container_name: altran-golang-portdomainservice
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - './:/tmp'
    ports:
      - "10001:10001"
      - "10002:10002"
      - "10003:10003"
    environment:
      GOMAXPROCS: "${GOMAXPROCS}"
      GRPC_ADDRESS: "${GRPC_ADDRESS}"
      SQLITE_PATH: "${SQLITE_PATH}"